const FN='https://uhhciyagfbaekeodwqcq.supabase.co/functions/v1/ai-english';
const DB='https://uhhciyagfbaekeodwqcq.supabase.co/rest/v1';
const KEY='sb_publishable_bv-gGuq-ihUFlnsPfYLF4w_9BKlpW-U';
const H={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'};
const cats=['全部','商务','日常','校园','旅行','科技','考试','口语','其他'];
let users=[];
let uid=localStorage.getItem('activeEnglishUser')||'11111111-1111-4111-8111-111111111111';
let S={tab:'home',filter:'全部',hfilter:'全部',items:[],tests:[]};
let loading=false;
function $(id){return document.getElementById(id)}
async function api(path,opt={}){const r=await fetch(DB+path,{...opt,headers:{...H,...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function user(){return users.find(x=>x.id===uid)||users[0]||{id:uid,name:'我',avatar:'我'}}
function sp(t){if(speechSynthesis){let u=new SpeechSynthesisUtterance(t);u.lang='en-US';speechSynthesis.speak(u)}}
function current(){return S.items.filter(i=>i.isInCurrentBook)}
function mastered(){return S.items.filter(i=>i.status==='已掌握')}
function dueItems(){let n=Date.now();return current().filter(i=>new Date(i.nextReviewAt||Date.now()).getTime()<=n)}
function syncText(t){let el=$('syncState');if(el)el.textContent=t}
function dbToItem(r){return{id:r.id,clientId:r.client_id,text:r.text,type:r.type,phonetic:r.phonetic||'',partOfSpeech:r.part_of_speech||'',definitionCn:r.definition_cn||'',definitionEn:r.definition_en||'',category:r.category||'其他',examples:r.examples_json||[],status:r.status||'学习中',masteryLevel:r.mastery_level||1,createdAt:r.created_at,updatedAt:r.updated_at,lastReviewedAt:r.last_reviewed_at,nextReviewAt:r.next_review_at||new Date().toISOString(),isInCurrentBook:r.is_in_current_book!==false,userId:r.user_id}}
function itemToRow(it){return{user_id:uid,client_id:it.clientId||it.id||crypto.randomUUID(),text:it.text,type:it.type||'word',phonetic:it.phonetic||'',part_of_speech:it.partOfSpeech||'',definition_cn:it.definitionCn||'',definition_en:it.definitionEn||'',category:it.category||'其他',examples_json:it.examples||[],status:it.status||'学习中',mastery_level:it.masteryLevel||1,next_review_at:it.nextReviewAt||new Date().toISOString(),last_reviewed_at:it.lastReviewedAt||null,is_in_current_book:it.isInCurrentBook!==false,updated_at:new Date().toISOString()}}
async function loadUsers(){try{users=await api('/demo_user_profiles?select=*&order=created_at.asc')}catch(e){users=[]}if(!users.length){users=[{id:'11111111-1111-4111-8111-111111111111',name:'我',avatar:'我'},{id:'22222222-2222-4222-8222-222222222222',name:'家人',avatar:'家'}]}if(!users.find(u=>u.id===uid))uid=users[0].id;localStorage.setItem('activeEnglishUser',uid)}
async function migrateLocalOnce(){const flag='cloudMigrated_'+uid;if(localStorage.getItem(flag))return;const raw=localStorage.getItem('englishAppV3_'+uid);if(!raw){localStorage.setItem(flag,'1');return}try{const old=JSON.parse(raw);const arr=old.items||[];for(const it of arr){const row=itemToRow({...it,clientId:it.clientId||it.id});await api('/vocabulary_items?on_conflict=user_id,client_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)})}localStorage.setItem(flag,'1')}catch(e){console.warn('local migrate failed',e)}}
async function loadCloud(){if(loading)return;loading=true;try{syncText('正在云同步...');await loadUsers();await migrateLocalOnce();const vs=await api('/vocabulary_items?select=*&user_id=eq.'+encodeURIComponent(uid)+'&order=created_at.desc');S.items=(vs||[]).map(dbToItem);try{S.tests=await api('/test_records?select=*&user_id=eq.'+encodeURIComponent(uid)+'&order=created_at.desc&limit=100')||[]}catch(e){S.tests=[]}syncText('云同步完成 '+new Date().toLocaleTimeString())}finally{loading=false}}
async function switchUser(id){uid=id;localStorage.setItem('activeEnglishUser',uid);S.items=[];S.tests=[];render();await loadCloud();render()}
async function addUser(){let name=prompt('输入新用户名称，例如：女儿 / 自己 / 用户D');if(!name)return;let id=crypto.randomUUID();let u={id,name:name.trim(),avatar:name.trim().slice(0,1)};await api('/demo_user_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(u)});uid=id;localStorage.setItem('activeEnglishUser',uid);await loadCloud();render()}
function renderUsers(){let u=user();$('avatar').textContent=u.avatar||u.name.slice(0,1);$('userSelect').innerHTML=users.map(x=>`<option value="${x.id}" ${x.id===uid?'selected':''}>${esc(x.name)}｜云同步词库</option>`).join('')}
async function ai(text,mode){let r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,mode,user:user().name})});let j=await r.json();if(j.error)throw Error(j.error);return j.data}
function norm(d,raw){return{clientId:crypto.randomUUID(),text:d.text||raw,type:d.type||'word',phonetic:d.phonetic||'',partOfSpeech:d.partOfSpeech||'',definitionCn:d.definitionCn||d.translation||'',definitionEn:d.definitionEn||'',category:d.category||'其他',examples:(d.examples||[]).map(x=>Array.isArray(x)?{en:x[0],cn:x[1]}:{en:x.en,cn:x.cn}),status:'学习中',masteryLevel:1,nextReviewAt:new Date().toISOString(),isInCurrentBook:true,userId:uid}}
function card(i,extra=''){let ex=(i.examples||[]).map(e=>Array.isArray(e)?{en:e[0],cn:e[1]}:e);return`<div class="card"><div class="word"><div><h3>${esc(i.text)}</h3><div class="muted">${esc(i.phonetic)} · ${esc(i.partOfSpeech)}</div></div><button class="ghost" onclick="sp('${esc(i.text)}')">🔊</button></div><p>${esc(i.definitionCn)}</p><p class="muted">${esc(i.definitionEn)}</p><span class="tag">${esc(i.category)}</span><span class="muted"> 阶段${i.masteryLevel} · ${new Date(i.nextReviewAt).toLocaleDateString()}</span><ol class="examples">${ex.map(e=>`<li>${esc(e.en)}<br><span class="muted">${esc(e.cn)}</span></li>`).join('')}</ol>${extra}</div>`}
function nav(){tabs.innerHTML=[['home','首页'],['book','生词本'],['test','测试'],['speak','口语'],['history','历史'],['review','复习']].map(([id,n])=>`<button class="tab ${S.tab===id?'active':''}" onclick="S.tab='${id}';render()">${n}</button>`).join('')}
function renderHome(){home.innerHTML=`<div class="statgrid"><div class="stat"><div class="num">${current().length}</div><div class="muted">当前生词</div></div><div class="stat"><div class="num">${dueItems().length}</div><div class="muted">今日复习</div></div><div class="stat"><div class="num">${mastered().length}</div><div class="muted">已掌握</div></div></div><div class="card"><h2>快速翻译</h2><textarea id="ti" class="input textarea" placeholder="输入中文或英文"></textarea><div class="actions"><button onclick="doTrans()">AI 翻译</button><button class="ghost" onclick="tr.classList.add('hidden')">清空</button></div><div id="tr" class="result hidden"></div></div><div class="card"><h2>添加到 ${esc(user().name)} 的云词库</h2><textarea id="nw" class="input textarea" placeholder="输入单词、短语或句子"></textarea><div class="actions"><button onclick="addWord()">AI分析并云保存</button></div><div class="muted" style="margin-top:10px">多台设备打开同一网址，选择同一用户即可同步。</div></div>`}
async function doTrans(){let v=ti.value.trim();if(!v)return;tr.classList.remove('hidden');tr.innerHTML='正在翻译...';try{let d=await ai(v,'translate');tr.innerHTML=`<b>${esc(v)}</b><br>翻译：${esc(d.translation)}<br>音标：${esc(d.phonetic)}<br>词性：${esc(d.partOfSpeech)}<br>中文释义：${esc(d.definitionCn)}<br>英文解释：${esc(d.definitionEn)}<br>分类：${esc(d.category)}<br><button class="ghost" onclick="sp('${esc(v)}')">播放发音</button>`}catch(e){tr.innerHTML='调用失败：'+esc(e.message)}}
async function addWord(){let v=nw.value.trim();if(!v)return;nw.value='';S.tab='book';render();book.innerHTML='<div class="card empty">AI 正在分析并同步到云端...</div>';try{let d=await ai(v,'vocabulary');let it=norm(d,v);let saved=await api('/vocabulary_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(itemToRow(it))});S.items.unshift(dbToItem(saved[0]));render()}catch(e){alert('AI分析失败：'+e.message);await loadCloud();render()}}
async function removeItem(id){await api('/vocabulary_items?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_in_current_book:false,status:'已移出',updated_at:new Date().toISOString()})});await loadCloud();render()}
function renderBook(){let list=current();if(S.filter!=='全部')list=list.filter(i=>i.category===S.filter);book.innerHTML=`<div class="card"><h2>${esc(user().name)} 的当前云词库</h2><div class="filters">${cats.map(c=>`<button class="chip ${S.filter===c?'active':''}" onclick="S.filter='${c}';render()">${c}</button>`).join('')}</div></div>${list.map(i=>card(i,`<div class="actions"><button class="light" onclick="removeItem('${i.id}')">移出当前生词本</button></div>`)).join('')||'<div class="card empty">当前没有生词</div>'}`}
function renderTest(){let i=(dueItems()[0]||current()[0]);if(!i){test.innerHTML='<div class="card empty">暂无可测试生词</div>';return}let ops=[i.definitionCn,'完全无关的意思','预约；计划','快速移动'].sort(()=>Math.random()-.5);test.innerHTML=`<div class="card"><h2>${esc(user().name)} 的云同步测试</h2><h3>${esc(i.text)}</h3><p>请选择正确中文释义：</p>${ops.map(o=>`<button class="test-option" onclick="ans('${i.id}',this,'${esc(o)}')">${esc(o)}</button>`).join('')}<div id="fb" class="result hidden"></div></div>`}
async function ans(id,b,a){let i=S.items.find(x=>x.id===id),ok=a===i.definitionCn;b.classList.add(ok?'ok':'bad');await api('/test_records',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:uid,client_id:crypto.randomUUID(),vocabulary_item_id:id,vocabulary_client_id:i.clientId,test_type:'英文选中文',question:i.text,user_answer:a,correct_answer:i.definitionCn,is_correct:ok,score:ok?100:0})});let patch=ok?{status:'已掌握',is_in_current_book:false,mastery_level:6,last_reviewed_at:new Date().toISOString(),next_review_at:new Date(Date.now()+30*864e5).toISOString(),updated_at:new Date().toISOString()}:{status:'需复习',next_review_at:new Date(Date.now()+864e5).toISOString(),updated_at:new Date().toISOString()};await api('/vocabulary_items?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});fb.innerHTML=ok?'回答正确：已从当前生词本移除，历史词库保留。':'未通过：继续保留，下一阶段复习。';fb.classList.remove('hidden');setTimeout(async()=>{await loadCloud();render()},900)}
function renderSpeak(){let i=current()[0];speak.innerHTML=i?`<div class="card"><h2>口语练习</h2><span class="tag">${esc(i.category)}</span><h3>目标词：${esc(i.text)}</h3><p>请用目标词回答：How would you use "${esc(i.text)}" in a real conversation?</p><div class="actions"><button onclick="sr.classList.remove('hidden');sr.innerHTML='识别结果：I want to use ${esc(i.text)} in daily English.<br><br>AI反馈：表达基本正确，建议放入更真实语境。'">🎙 模拟录音</button><button class="ghost" onclick="sp('${esc(i.text)}')">播放</button></div><div id="sr" class="result hidden"></div></div>`:'<div class="card empty">暂无口语练习词</div>'}
function renderHistory(){let list=S.items;if(S.hfilter!=='全部')list=list.filter(i=>i.status===S.hfilter);history.innerHTML=`<div class="card"><h2>${esc(user().name)} 的历史云词库</h2><div class="filters">${['全部','学习中','需复习','已掌握','已移出'].map(s=>`<button class="chip ${S.hfilter===s?'active':''}" onclick="S.hfilter='${s}';render()">${s}</button>`).join('')}</div></div>${list.map(i=>card(i,`<div class="muted">状态：${esc(i.status)} · ${i.isInCurrentBook?'当前生词本中':'不在当前生词本'}</div>`)).join('')||'<div class="card empty">历史词库为空</div>'}`}
function renderReview(){let d=dueItems(),soon=current().filter(i=>!d.includes(i));review.innerHTML=`<div class="card"><h2>${esc(user().name)} 的复习计划</h2><p class="muted">间隔重复：当天 → 1天 → 3天 → 7天 → 15天 → 30天。</p><div class="actions"><button class="ghost" onclick="manualRefresh()">手动云同步</button></div></div><div class="card"><h3>今日需复习</h3>${d.map(i=>`<p><b>${esc(i.text)}</b> <span class="tag">阶段${i.masteryLevel}</span></p>`).join('')||'<p class="muted">今天没有到期词。</p>'}</div><div class="card"><h3>即将复习</h3>${soon.map(i=>`<p><b>${esc(i.text)}</b><br><span class="muted">${new Date(i.nextReviewAt).toLocaleString()}</span></p>`).join('')||'<p class="muted">暂无即将复习词。</p>'}</div>`}
function render(){renderUsers();document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(S.tab).classList.remove('hidden');due.textContent='今日 '+dueItems().length;nav();({home:renderHome,book:renderBook,test:renderTest,speak:renderSpeak,history:renderHistory,review:renderReview}[S.tab])()}
async function manualRefresh(){await loadCloud();render()}
async function init(){render();try{await loadCloud();render()}catch(e){home.innerHTML='<div class="card empty">云同步加载失败：'+esc(e.message)+'</div>';renderUsers();nav();syncText('云同步失败')}}
window.addEventListener('focus',manualRefresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)manualRefresh()});setInterval(manualRefresh,30000);
init();